name: Deploy Azure Button

on:
  push:
    branches:
      - master

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-builder.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3

    - name: matrix-builder
      id: matrix-builder
      uses: ./.github/actions/build-matrix

    - name: debug
      run: echo ${{ steps.matrix-builder.outputs.matrix }}

  add-azure-bicep:
    needs:
      - generate-matrix
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v3

    - name: generate-bicep
      id: generate-bicep
      uses: ./.github/actions/generate-bicep
      env:
        folderPath: ${{ matrix.folder }}

    - name: push-update
      run: |
        ls -R
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure ARM template"
        git pull --rebase
        git push

  add-azure-arm-template:
    needs:
      - generate-matrix
      - add-azure-bicep
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Bicep Build
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: '${{ matrix.folder }}/query.bicep'
        outputFilePath: '${{ matrix.folder }}/azuredeploy.json'

    - name: push-update
      run: |
        ls -R
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure ARM template"
        git pull --rebase
        git push

  add-azure-deploy-button:
    needs:
      - add-azure-arm-template
      - add-azure-bicep
      - generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix)  }}

    steps:
    - uses: actions/checkout@v3

    - name: rebase-before-run
      run: |
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git pull --rebase

    - name: generate-deploy-button
      id: generate-deploy-button
      uses: wilfriedwoivre/action-deploy-azure-button@v1.1
      env:
        templatePath: '${{ matrix.folder }}/azuredeploy.json'
        markdownPath: '${{ matrix.folder }}/README.md'
      

    - name: debug
      run: echo ${{ steps.generate-deploy-button.outputs.fileUpdated }}

    - name: push-update
      if: steps.generate-deploy-button.outputs.fileUpdated == 'True'
      run: |
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure deploy button"
        git pull --rebase
        git push
      
       
        
